### ISSUE TITLE
Update the plugin so it works with the new 2023.4 (the 2nd Snapshot)

### ISSUE THREAD

**Issue by furti-two** [Spectrall368/Generator-1.19.2#1]

**Comment by Spectrall368** [comment]
I wanted to wait for the 2023.4 release but since you're asking ok, I'll do it for the second snapshot

**Comment by furti-two** [comment]
Thank you so much! I’m working on a whole rework of Stalwart Dungeons on a Mcreator snapshots

**Comment by Spectrall368** [comment]
Done!
