### ISSUE TITLE
error: local variables referenced from a lambda expression must be final or effectively final

### ISSUE THREAD

**Issue by JeanWorldTour2** [Spectrall368/Generator-1.19.2#10]
I'm sorry but i've found another bug and checked if it's one of the other plugins, but it's this one again here is a error log
Executing Gradle task: runClient 
Build info: MCreator 2024.1.18518, forge-1.19.2, 64-bit, 14283 MB, Windows 11, JVM 17.0.10, JAVA_HOME: D:\Program Files\MCreator 2024.1\MCreator\jdk, started on: 2024-05-15-19:15:26 
 
> Task :compileJava 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:75: error: local variables referenced from a lambda expression must be final or effectively final 
                if ((!world.getEntitiesOfClass(Player.class, AABB.ofSize(new Vec3(x, y, z), 1, 1, 1), e -> true).isEmpty() || !world.getEntitiesOfClass(ServerPlayer.class, AABB.ofSize(new Vec3(x, y, z), 1, 1, 1), e -> true).isEmpty()) 
                      ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:75: error: local variables referenced from a lambda expression must be final or effectively final 
                if ((!world.getEntitiesOfClass(Player.class, AABB.ofSize(new Vec3(x, y, z), 1, 1, 1), e -> true).isEmpty() || !world.getEntitiesOfClass(ServerPlayer.class, AABB.ofSize(new Vec3(x, y, z), 1, 1, 1), e -> true).isEmpty()) 
                                                                                                                               ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:83: error: local variables referenced from a lambda expression must be final or effectively final 
                        }.getValue(world, new BlockPos(x, y - 1, z), "RedstoneOn")) == true) { 
                                   ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:106: error: local variables referenced from a lambda expression must be final or effectively final 
                if (!world.isClientSide()) { 
                     ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:108: error: local variables referenced from a lambda expression must be final or effectively final 
                    BlockEntity _blockEntity = world.getBlockEntity(_bp); 
                                               ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:109: error: local variables referenced from a lambda expression must be final or effectively final 
                    BlockState _bs = world.getBlockState(_bp); 
                                     ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:112: error: local variables referenced from a lambda expression must be final or effectively final 
                    if (world instanceof Level _level) 
                        ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:115: error: local variables referenced from a lambda expression must be final or effectively final 
                if (SoulGlowstoneModVariables.MapVariables.get(world).Backrooms_Generated == false) { 
                                                               ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:138: error: local variables referenced from a lambda expression must be final or effectively final 
                    if (world instanceof ServerLevel _origLevel) { 
                        ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:139: error: local variables referenced from a lambda expression must be final or effectively final 
                        LevelAccessor _worldorig = world; 
                                                   ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:140: error: local variables referenced from a lambda expression must be final or effectively final 
                        world = _origLevel.getServer().getLevel(ResourceKey.create(Registry.DIMENSION_REGISTRY, new ResourceLocation("soul_glowstone:backroom"))); 
                        ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:141: error: local variables referenced from a lambda expression must be final or effectively final 
                        if (world != null) { 
                            ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:142: error: local variables referenced from a lambda expression must be final or effectively final 
                            world.setBlock(new BlockPos(1, 20, 1), SoulGlowstoneModBlocks.ROOM_PLACER.get().defaultBlockState(), 3); 
                            ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:151: error: local variables referenced from a lambda expression must be final or effectively final 
                            SoulGlowstoneModVariables.MapVariables.get(world).Backrooms_Generated = true; 
                                                                       ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:152: error: local variables referenced from a lambda expression must be final or effectively final 
                            SoulGlowstoneModVariables.MapVariables.get(world).syncData(world); 
                                                                       ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:152: error: local variables referenced from a lambda expression must be final or effectively final 
                            SoulGlowstoneModVariables.MapVariables.get(world).syncData(world); 
                                                                                       ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:154: error: local variables referenced from a lambda expression must be final or effectively final 
                        world = _worldorig; 
                        ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:193: error: local variables referenced from a lambda expression must be final or effectively final 
                if ((!world.getEntitiesOfClass(Player.class, AABB.ofSize(new Vec3(x, y, z), 1, 1, 1), e -> true).isEmpty() || !world.getEntitiesOfClass(ServerPlayer.class, AABB.ofSize(new Vec3(x, y, z), 1, 1, 1), e -> true).isEmpty()) 
                      ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:193: error: local variables referenced from a lambda expression must be final or effectively final 
                if ((!world.getEntitiesOfClass(Player.class, AABB.ofSize(new Vec3(x, y, z), 1, 1, 1), e -> true).isEmpty() || !world.getEntitiesOfClass(ServerPlayer.class, AABB.ofSize(new Vec3(x, y, z), 1, 1, 1), e -> true).isEmpty()) 
                                                                                                                               ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:201: error: local variables referenced from a lambda expression must be final or effectively final 
                        }.getValue(world, new BlockPos(x, y - 1, z), "RedstoneOn")) == true) { 
                                   ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:211: error: local variables referenced from a lambda expression must be final or effectively final 
                        }.getValue(world, new BlockPos(x, y - 1, z), "TelePosX")), (new Object() { 
                                   ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:218: error: local variables referenced from a lambda expression must be final or effectively final 
                        }.getValue(world, new BlockPos(x, y - 1, z), "TelePosY")), (new Object() { 
                                   ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:225: error: local variables referenced from a lambda expression must be final or effectively final 
                        }.getValue(world, new BlockPos(x, y - 1, z), "TelePosZ"))); 
                                   ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:234: error: local variables referenced from a lambda expression must be final or effectively final 
                            }.getValue(world, new BlockPos(x, y - 1, z), "TelePosX")), (new Object() { 
                                       ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:241: error: local variables referenced from a lambda expression must be final or effectively final 
                            }.getValue(world, new BlockPos(x, y - 1, z), "TelePosY")), (new Object() { 
                                       ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:248: error: local variables referenced from a lambda expression must be final or effectively final 
                            }.getValue(world, new BlockPos(x, y - 1, z), "TelePosZ")), _ent.getYRot(), _ent.getXRot()); 
                                       ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:251: error: local variables referenced from a lambda expression must be final or effectively final 
                if (!world.isClientSide()) { 
                     ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:253: error: local variables referenced from a lambda expression must be final or effectively final 
                    BlockEntity _blockEntity = world.getBlockEntity(_bp); 
                                               ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:254: error: local variables referenced from a lambda expression must be final or effectively final 
                    BlockState _bs = world.getBlockState(_bp); 
                                     ^ 
D:\MCreatorWorkspaces\soul_glowstone\src\main\java\net\mcreator\soul_glowstone\procedures\TeleportFieldEntityCollidesInTheBlockProcedure.java:257: error: local variables referenced from a lambda expression must be final or effectively final 
                    if (world instanceof Level _level) 
                        ^ 
30 errors 
> Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler error output for details. 
* Try: 
> Run with --info option to get more log output. 
> Run with --scan to get full insights. 
BUILD FAILED in 12s 
1 actionable task: 1 executed 
 
BUILD FAILED 
Task completed in 18 seconds 

The arrow is at every "world" word
![image](https://github.com/Spectrall368/Generator-1.19.2/assets/133048466/776429e8-95b3-45bf-bb04-7027b183b6ce)

**Comment by JeanWorldTour2** [comment]
Please i NEED this to be fixed, on the may 24th there needs to be a mod uploaded PLEASE do it so fast as you can possibly be plase :(

**Comment by Spectrall368** [comment]
can you send me the workspace?

**Comment by JeanWorldTour2** [comment]
https://www.transfernow.net/dl/20240519a5DEqhSv you have 7 days to download this

**Comment by Spectrall368** [comment]
Ok

**Comment by Spectrall368** [comment]
your workspace is using plugins, remove the plugins and try again

**Comment by JeanWorldTour2** [comment]
I'm sorry that I was not responding i was gone for a week and it won't work even if all plugins that i can remove are gone
![image](https://github.com/Spectrall368/Generator-1.19.2/assets/133048466/d5bb1e01-7e16-4ff3-837b-bad8adc6d2d2)

**Comment by JeanWorldTour2** [comment]
nvm
