### ISSUE TITLE
Error in textures applied to item and block in 2024.1

### ISSUE THREAD

**Issue by Dioooooooos** [Spectrall368/Generator-1.19.2#11]
While using the latest 2024.1 generator, I noticed that all my item and block textures were missing. After some investigation, I found that the generator's JSON files set the texture source to "block" and "item", whereas the workspace's texture folders are named "blocks" and "items". I spent some time fixing them (approximately), and now I have uploaded them to Mega. I hope you can take a look.
https://mega.nz/file/ZvIgASBC#npyNv2lf6JX6tWvHbvaphG1L633BZvxJe_vsmiCNYN4

**Comment by Spectrall368** [comment]
In the new generators the folders are called that way, so I renamed them accordingly in this generator too, to fix this bug you have to rename the folders
