### ISSUE TITLE
GeckoLib import issue

### ISSUE THREAD

**Issue by RipleyMods** [Spectrall368/Generator-1.19.2#12]
When i convert my workspace from 1.20.1 to 1.19.2, every single element comes back as an error. Is this an issue on my side?

**Comment by RipleyMods** [comment]
I’m aware you said that support for lower than MCreator 2024.2 is ending, but seeing as I also know you aren’t going to do a 1.20.1 generator, I have no option but to hope for a fix for this for 2024.1, so I can develop mods in versions 1.20.1 and 1.19.2, as I don’t plan to update MCreator to 2024.2 unless there is a way to develop 1.20.1 mods in it, and I certainly won’t ask you to spend the time making the 1.20.1 generator.

**Comment by Spectrall368** [comment]
1.20.1 is also supported in MCreator 2024.2 (which this generator will support), could you send the mcreator logs?

**Comment by RipleyMods** [comment]
Really? To my knowledge Mcreator 2024.2 natively supports only Neoforge 1.20.4 and 1.20.6, if that’s true then that is great news. I can provide the logs later tonight as I am away from my PC, thanks for the quick response!

**Comment by Spectrall368** [comment]
> Really? To my knowledge Mcreator 2024.2 natively supports only Neoforge 1.20.4 and 1.20.6, if that’s true then that is great news. I can provide the logs later tonight as I am away from my PC, thanks for the quick response!

Thank you for reporting this bug
![image](https://github.com/user-attachments/assets/44de70f5-87f2-4ca6-a252-858db942d0c9)

**Comment by RipleyMods** [comment]
Insane that I missed that. I’ll still send you the logs for the 2024.1 version, but awesome that 2024.2 supports it (I personally am not a fan of neoforge so I was desperately trying to maintain a 1.20.1 development) appreciate the time.

**Comment by RipleyMods** [comment]
Executing Gradle task: build
Build info: MCreator 2024.1.18518, forge-1.19.2, 64-bit, 32486 MB, Windows 11, JVM 17.0.10, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2024-07-20-22:49:27
Loaded APIs: geckolib

> Task :compileJava
[22:49:38] [main/INFO]: Writing debug log file accesstransform.log
[22:49:38] [main/INFO]: Access Transformer processor running version 8.2.0
[22:49:38] [main/INFO]: Command line arguments [--inJar, C:\Users\jason\OneDrive\Desktop\Lwtest\build\fg_cache\net\minecraftforge\forge\1.19.2-43.3.5\forge-1.19.2-43.3.5-injected.jar, --outJar, C:\Users\jason\OneDrive\Desktop\Lwtest\build\fg_cache\net\minecraftforge\forge\1.19.2-43.3.5_mapped_official_1.19.2\forge-1.19.2-43.3.5_mapped_official_1.19.2.jar, --logFile, accesstransform.log, --atFile, C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\resources\META-INF\accesstransformer.cfg, --atFile, C:\Users\jason\OneDrive\Desktop\Lwtest\build\_atJar_4\parent_at.cfg]
[22:49:38] [main/INFO]: Reading from C:\Users\jason\OneDrive\Desktop\Lwtest\build\fg_cache\net\minecraftforge\forge\1.19.2-43.3.5\forge-1.19.2-43.3.5-injected.jar
[22:49:38] [main/INFO]: Writing to C:\Users\jason\OneDrive\Desktop\Lwtest\build\fg_cache\net\minecraftforge\forge\1.19.2-43.3.5_mapped_official_1.19.2\forge-1.19.2-43.3.5_mapped_official_1.19.2.jar
[22:49:38] [main/INFO]: Transformer file C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\resources\META-INF\accesstransformer.cfg
[22:49:38] [main/INFO]: Transformer file C:\Users\jason\OneDrive\Desktop\Lwtest\build\_atJar_4\parent_at.cfg
[22:49:38] [main/WARN]: Found existing output jar C:\Users\jason\OneDrive\Desktop\Lwtest\build\fg_cache\net\minecraftforge\forge\1.19.2-43.3.5_mapped_official_1.19.2\forge-1.19.2-43.3.5_mapped_official_1.19.2.jar, overwriting
[22:49:40] [main/INFO]: JAR transformation complete C:\Users\jason\OneDrive\Desktop\Lwtest\build\fg_cache\net\minecraftforge\forge\1.19.2-43.3.5_mapped_official_1.19.2\forge-1.19.2-43.3.5_mapped_official_1.19.2.jar
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Acaciashelf2Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Acaciashelf3Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Acaciashelf4Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AcaciashelfBlock.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Acaciatable2Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Acaciatable3Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Acaciatable4Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AcaciatableBlock.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AncientChiseledHalfSandstoneBricksBlock.java:12: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AncientCrackedSandstoneBricksBlock.java:12: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AncientHalfsandstonebricksBlock.java:12: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AncientSandstonebricksBlock.java:12: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AncientSandstoneSlabBlock.java:9: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AncientSandstoneStairsBlock.java:11: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AuburnDoorBlock.java:11: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AuburnlogBlock.java:18: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AuburnSaplingBlock.java:26: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Auburnshelf2Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Auburnshelf3Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Auburnshelf4Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AuburnshelfBlock.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Auburntable2Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Auburntable3Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Auburntable4Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AuburntableBlock.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AuburntrapdoorBlock.java:11: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AuburnWoodBlock.java:18: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AutumnfenceBlock.java:13: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AutumnfencegateBlock.java:13: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AutumnleavesBlock.java:16: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AutumnplankBlock.java:13: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AutumnslabBlock.java:13: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\AutumnstairsBlock.java:14: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BaobabDoorBlock.java:11: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BaobabfenceBlock.java:13: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BaobabFenceGateBlock.java:15: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BaoBabLeavesBlock.java:19: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BaoBabSaplingBlock.java:26: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BaobabSlabBlock.java:13: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BaobabStairsBlock.java:14: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BaobabtrapdoorBlock.java:11: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BaoBobLogBlock.java:18: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BaobobPlankBlock.java:13: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BaoBobWoodBlock.java:18: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Baoshelf1Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Baoshelf2Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Baoshelf3Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Baoshelf4Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Baotable2Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Baotable3Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Baotable4Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BaotableBlock.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Birchshelf1Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Birchshelf2Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Birchshelf3Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Birchshelf4Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Birchtable2Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Birchtable3Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Birchtable4Block.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BirchtableBlock.java:24: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BirchtreemushroomsBlock.java:26: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlackberrybushBlock.java:19: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlackBerryStage0Block.java:23: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlackBerryStage1Block.java:20: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlackBerryStage2Block.java:23: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlackFireBlock.java:31: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlackIshBrickBlock.java:12: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlackIshSlabBlock.java:9: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlackIshStairsBlock.java:11: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlackIshWallBlock.java:9: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlackPatternedIshBricksBlock.java:12: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlueberrybushBlock.java:19: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Blueberrystage0Block.java:23: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlueberryStage1Block.java:20: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlueberryStage2Block.java:22: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlueFireBlock.java:28: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlueishbrickBlock.java:12: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlueIshSlabBlock.java:9: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlueIshStairsBlock.java:11: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BlueIshWallBlock.java:9: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BluePatternedIshBricksBlock.java:12: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BluePetuniaPot2Block.java:38: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BluePetuniaPot3Block.java:32: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BluePetuniaPot4Block.java:32: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BluePetuniaPotBlock.java:32: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BluePetuniasBlock.java:16: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BoneStalkerTrophyBlock.java:27: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BookstackBlock.java:27: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BookstackthreeBlock.java:27: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BookstacktwoBlock.java:27: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BrownIshbrickBlock.java:12: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BrownIshSlabBlock.java:9: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BrownIshStairsBlock.java:11: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BrownIshWallBlock.java:9: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\BrownPatternedIshBricksBlock.java:12: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Clovers1Block.java:18: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Clovers2Block.java:21: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Clovers3Block.java:21: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Clovers4Block.java:21: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
C:\Users\jason\OneDrive\Desktop\Lwtest\src\main\java\net\mcreator\luminousworld\block\Clovers5Block.java:21: error: a type with the same simple name is already defined by the single-type-import of Material import net.minecraft.client.resources.model.Material;
^
100 errors
only showing the first 100 errors, of 1004 total; use -Xmaxerrs if you would like to see more
> Task :compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.
BUILD FAILED in 25s
1 actionable task: 1 executed

BUILD FAILED
Task completed in 20 minutes and 22 seconds
~~~~~~~~~~~~~~~~~~~~~~~~~~~~


This is what my console error looks like.

**Comment by RipleyMods** [comment]
I believe I found the source of this error. I believe it's an error in compatibility with the geckolib plugin and how the code is rebuilt. Doesn't really sound like something you have the ability to fix on your end unfortunately, because your generators have worked fine with geckolib in the past, but since geckolib updates more regularly I'm guessing that plugin is the issue. Any idea what causes something like this from a coding standpoint? Something that someone like me with too much free time could figure out how to fix? Any help is appreciated, thanks again for the time!

**Comment by Spectrall368** [comment]
it's a GeckoLib plugin issue, that plugin "overrides" some files of this one, and if I updated some of them and then the creator of the GeckoLib plugin doesn't it could give errors like this, this error is due to a missing line of code in the generator.yaml file of 1.19.2 in the GeckoLib plugin. Issue that I had already reported to the creator on discord and which he will not fix because it will no longer support that version

**Comment by RipleyMods** [comment]
Appreciate the info. I had a similar run in with the geckolib creator, he was quite rude. Shame, but maybe one day he'll fix this.

**Comment by RipleyMods** [comment]
Also, if I was to edit the geckolib file and add in this missing code myself, could it hypothetically work?

**Comment by Spectrall368** [comment]
> Also, if I was to edit the geckolib file and add in this missing code myself, could it hypothetically work?

Maybe yes
