### ISSUE TITLE
Compatibility with plugins (File Manager and ArrayList)

### ISSUE THREAD

**Issue by Iserion** [Spectrall368/Generator-1.19.2#13]
Hello, can you make it compatible with one or both of those plugins ? actually when i install those plugin, i can't choose the variable type with new variable type added by the plugins

**Comment by Spectrall368** [comment]
> Hello, can you make it compatible with one or both of those plugins ? actually when i install those plugin, i can't choose the variable type with new variable type added by the plugins

sorry for the delay, but I don't intend to support these plugins, you have to ask the creator himself to add support for this version
