### ISSUE TITLE
Biome code isn't generated

### ISSUE THREAD

**Issue by amungusisuk** [Spectrall368/Generator-1.19.2#2]
![image](https://github.com/Spectrall368/Generator-1.19.2/assets/153297077/3ccb8ef7-f2bb-48a3-8ccd-886f75e09aa9)

Я просто хотел создать мод на версии 1.19.2 но тут ...
Я не знаю что делать прошу исправить баг...

**Comment by Spectrall368** [comment]
Ok, It would be better if you wrote in English

**Comment by Spectrall368** [comment]
What version of MCreator are you using?

**Comment by amungusisuk** [comment]
> What version of MCreator are you using?

2023.4 , this is javacompile error idk why :(

**Comment by Spectrall368** [comment]
> > What version of MCreator are you using?
> 
> 2023.4 , this is javacompile error idk why :(

Are you using the latest MCreator 2023.4 patch?

**Comment by Spectrall368** [comment]
Also update the plugin to the latest version

**Comment by amungusisuk** [comment]
I downloaded the patch and now the error is gone, but when I try to create an entity it starts appearing again until I delete my entity :(((

**Comment by Spectrall368** [comment]
> I downloaded the patch and now the error is gone, but when I try to create an entity it starts appearing again until I delete my entity :(((

Strange, could you send me a photo of the MCreator plugins screen and could you send me a copy of the workspace that contains this error?

**Comment by amungusisuk** [comment]
> > I downloaded the patch and now the error is gone, but when I try to create an entity it starts appearing again until I delete my entity :((( .... 
> 
> Strange, could you send me a photo of the MCreator plugins screen and could you send me a copy of the workspace that contains this error?

The fact is that this happens in all workspaces 
, not only in 1, reinstallation does not help and creating new workspaces too...... hmm, now it won’t let me create even biome element...

![Снимок экрана 2024-01-14 154552](https://github.com/Spectrall368/Generator-1.19.2/assets/153297077/bc2e7e2b-f7e3-4b84-8445-6d11c6b36eb0)

![Снимок экрана 2024-01-14 154434](https://github.com/Spectrall368/Generator-1.19.2/assets/153297077/cfb14999-ff53-428c-8dc5-94d15035a40c)

**Comment by Spectrall368** [comment]
> > > I downloaded the patch and now the error is gone, but when I try to create an entity it starts appearing again until I delete my entity :((( ....
> > 
> > 
> > Strange, could you send me a photo of the MCreator plugins screen and could you send me a copy of the workspace that contains this error?
> 
> The fact is that this happens in all workspaces , not only in 1, reinstallation does not help and creating new workspaces too...... hmm, now it won’t let me create even biome element...

here I read that the version of the plugin you installed is 1.2.1 but currently the most recent version is 1.3.2 so update the plugin and try again
