### ISSUE TITLE
Plant element causing build error

### ISSUE THREAD

**Issue by kotishe666** [Spectrall368/Generator-1.19.2#3]
Whenever I'm trying to compile the mod, a plant element cause an error, telling me that it cannot register the plant as an item(I guess).
MCreator 2023.4
![image](https://github.com/Spectrall368/Generator-1.19.2/assets/136707176/eb6779c0-24e4-4358-8bf4-98d1e47cbaab)

**Comment by Spectrall368** [comment]
I will check

**Comment by Spectrall368** [comment]
I can't reproduce it, could you reproduce it in a example workspace?

**Comment by kotishe666** [comment]
I'll try, gimme a minute

**Comment by kotishe666** [comment]
Created a new workspace, the issue still appears. Maybe its somewhat related to geckolib?
![image](https://github.com/Spectrall368/Generator-1.19.2/assets/136707176/681e6efe-527d-4fcb-84bf-85b7e02bd51a)
Heres also the list of plugins I use
![image](https://github.com/Spectrall368/Generator-1.19.2/assets/136707176/396350f6-3740-42a5-a572-d9380ac577c9)

**Comment by kotishe666** [comment]
Tried to remove the configuration files and attributes plugins, the issue is still there

**Comment by Spectrall368** [comment]
Try removing GeckoLib

> Tried to remove the configuration files and attributes plugins, the issue is still there

**Comment by kotishe666** [comment]
Removed geckolib, the issue is gone.

**Comment by Spectrall368** [comment]
> Removed geckolib, the issue is gone.

Please report it to the creator of the Geckolib plugin and not here: https://github.com/NerdyPuzzle/MCreator-Nerdys_Geckolib_Plugin/issues
