### ISSUE TITLE
Mcitems doesn't correctly generate json blocks/Items

### ISSUE THREAD

**Issue by kotishe666** [Spectrall368/Generator-1.19.2#4]
One of advancements of my mod is granted whenever the player eats specific custom food. After updating the MCreator and this plugin, I found out that it stopped working. There is no build error, its just doesn't give you an advancement if specified item is consumed.

MCreator 2023.4
Latest plugin version

**Comment by Spectrall368** [comment]
I will check

**Comment by kotishe666** [comment]
So, have you checked the issue?

**Comment by kotishe666** [comment]
Ooops

**Comment by Spectrall368** [comment]
> So, have you checked the issue?

Not yet

**Comment by Spectrall368** [comment]
I understand the error, I just need to figure out where it's coming from to fix it

**Comment by Spectrall368** [comment]
It will be fixed in 2024.1
