### ISSUE TITLE
sound file same name

### ISSUE THREAD

**Issue by MARK42IRPC** [Spectrall368/Generator-1.19.2#9]
when i use this gennerator(2024.1;1.4.2) open my workspace,it runs worn,and tell me this.
GPT says that sound fale in same name

net.minecraft.world.level.material 中的类 net.minecraft.world.level.material.Material 和 net.minecraft.client.resources.model 中的类 net.minecraft.client.resources.model.Material 都匹配 
C:\MCreatorWorkspaces\traffic_tools_sign\src\main\java\net\mcreator\traffictoolssign\block\ZhuYiLuoShiBlock.java:34: 错误: 对Material的引用不明确 
        super(BlockBehaviour.Properties.of(Material.METAL).sound(SoundType.LANTERN).strength(1f, 10f).noOcclusion().isRedstoneConductor((bs, br, bp) -> false));
注: 某些输入文件使用或覆盖了已过时的 API。 
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。 
注: 某些输入文件使用了未经检查或不安全的操作。 
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。 
100 个错误 
仅显示前 100 个错误（共 104 个）；若要查看更多错误，请使用 -Xmaxerrs

same waring in every block mod element
i don't know how to solve,mabey becouse of this gennerator,could you help me?thank u very much

**Comment by Spectrall368** [comment]
can you send me the workspace?

**Comment by MARK42IRPC** [comment]
> can you send me the workspace?

file size is too big，it tells me”File size too big: 25 MB are allowed, 49 MB were attempted to upload.“

**Comment by MARK42IRPC** [comment]
do you have person email？maybe i can use this

> 你能把工作区发给我吗？

**Comment by Spectrall368** [comment]
> > can you send me the workspace?
> 
> file size is too big，it tells me”File size too big: 25 MB are allowed, 49 MB were attempted to upload.“

upload it to Google drive

**Comment by MARK42IRPC** [comment]
> > > can you send me the workspace?
> > 
> > 
> > file size is too big，it tells me”File size too big: 25 MB are allowed, 49 MB were attempted to upload.“
> 
> upload it to Google drive

thank u！！yes i can，this is https://drive.google.com/file/d/1lXq3rqavqPnJsq0LIjj5g8vDNn1htwCs/view?usp=sharing
my mod element use some chineseENGword name，so it looks hard to understand these block is what things，sorry
thank u very much！
thank u very much！thank u very much！thank u very much！

**Comment by Spectrall368** [comment]
It doesn't give me any errors

![image](https://github.com/Spectrall368/Generator-1.19.2/assets/105946758/b792df71-b2ca-4ee0-a085-8a3cc5b02a2f)

**Comment by Spectrall368** [comment]
try regenerating the code

**Comment by MARK42IRPC** [comment]
> try regenerating the code

i tryed many times, still error.i show it to you later.

**Comment by MARK42IRPC** [comment]
> It doesn't give me any errors

https://drive.google.com/file/d/1bpNZL3c5I0VmfnL2owmmvB3izCqo4SXf/view?usp=sharing
in English and Chinese，warning not same
and when i launch，it say error to load this generator，but i can use it launch workspace

**Comment by Spectrall368** [comment]
It seems like you are using other plugins try checking this folder: /.mcreator/plugins and try to regenerate the code using this button: 
![image](https://github.com/Spectrall368/Generator-1.19.2/assets/105946758/d49d27c9-7abc-4b81-9420-5f2b83a9f58c)

**Comment by MARK42IRPC** [comment]
ok，thanks，i change language to english and use this button，it work now
thank you very much！

**Comment by Spectrall368** [comment]
you're welcome
